config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists
    resources :items, only: [:new, :create, :update]
end

  root 'lists#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
    has_many :items
    validates_presence_of :name, message: 'debes escribir un nombre'
    validates :name, format: {with: /\D/, message: 'solo puede llevar letras'}
    validates :name, length: {minimum: 3, message: 'debe tener un mínimo de 3 caracteres'}
    validates :name, length: {maximum: 30, message: 'debe tener un máximo de 30 caracteres'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def new
        @item = Item.new
        @list = List.find(params[:list_id])
    end
    def create
        @item = Item.new(item_params)
        @item.list_id = params[:list_id]

        if @item.save
            redirect_to list_path(params[:list_id]), notice: 'item añadido'
        else
            render :new
        end
    end

    def update
        @item = Item.find(params[:id])
        @item.update(done: !@item.done)
        redirect_to list_path(params[:list_id])
    end

    private
    def item_params
        params.require(:item).permit(:name)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

    def index
        @lists = List.all
    end

    def show
        @list = List.find(params[:id])
    end

    def new
        @list = List.new
    end

    def create
        @list = List.new(list_params)

        if @list.save
            redirect_to root_path, notice: 'se ha creado una nueva lista'
        else
            render :new
        end
    end

    private
    def list_params
        params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/new.html.erb
<h1>Nuevo item</h1>

<%= form_with(model:[@list, @item], local: true) do |f| %>

    <% if @item.errors.any? %>
        <% @item.errors.full_messages.each do |message|%>
            <p><%= message %></p>
        <%end%>
    <%end%>

    <div>
        <%= f.label :name, 'nombre del item'%>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.submit 'guardar'%>
    </div>
<%end%>

<%= link_to 'volver a la lista', list_path(@list.id)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Worklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice%>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Todas las listas</h1>

<%= link_to 'Nueva lista', new_list_path %>

<table>
    <thead>
        <th>Nombre de la lista</th>
        <th>Creada</th>
        <th>Tareas</th>
    </thead>

    </tbody>
        <% @lists.each do |list| %>
            <tr>
                <td><%= list.name%></td>
                <td><%= list.created_at%></td>
                <td><%= link_to 'ver tareas', list_path(list.id) %></td>
            </tr>
        <%end%>
    </tbody>
</table>

app/views/lists/new.html.erb
<h1>Nueva lista</h1>

<%= form_with(model: @list, local: true) do |f| %>

    <% if @list.errors.any? %>
        <% @list.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <%end%>
    <%end%>

    <div>
        <%= f.label :name, 'Nombre' %>
        <%= f.text_field :name, placeholder: 'pon el nombre de la lista aqui'%>
    </div>

    <div>
        <%= f.submit 'guardar'%>
    </div>
<%end%>

app/views/lists/show.html.erb
<h1>Vista de lista de tareas</h1>

<p>Nombre: <%= @list.name %></p>

<h3>Items</h3>

<ul>
    <li><%= link_to 'añadir item', new_list_item_path(@list.id) %></li>
    <% @list.items.each do |item|%>
        <li><%=item.name%> | <%item.done ? 'lista' : 'en proceso' %><%= link_to raaw ('&#10004'), list_item_path(@list.id, item.id), method: :patch%></li>
    <%end%>
</ul>